django/learning_log/users/urls.py
"""Определяет схемы URL для пользователей"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    #Включить URL авторизации по умолчанию
    path ('', include('django.contrib.auth.urls')),
    #Страница регистрации
    path ('register/', views.register, name='register'),

]

django/learning_log/users/models.py
from django.db import models

# Create your models here.

django/learning_log/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


# Create your views here.
def register(request):
    """Регистрирует нового пользователя"""
    if request.method != 'POST':
        #Выводит пустую форму регистрации
        form = UserCreationForm()
    else:
        #Обработка заполненной формы
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            #Выполнение входа и перенаправление на другую страницу
            login(request, new_user)
            return redirect('learning_logs:index')

    context = {'form': form}
    return render(request, 'users/register.html', context)

django/learning_log/users/templates/users/register.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
    <h1>Register a new user</h1p>
{%endblock page_header%}

{% block content %}

    <!--<form method="post" action="{% url 'users:register' %}">
        {% csrf_token %}
        {{ form.as_p }}
        
        <button name="submit">register</button>
        <input type="hidden" name="next"
          value="{% url 'learning_logs:index' %}" />
    </form>-->

    <form method="post" action="{% url 'users:register' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Register</button>
        {% endbuttons %}
        <input type="hidden" name="next"
          value="{% url 'learning_logs:index' %}" />
    </form>


{% endblock content %}