django/learning_log/learning_logs/urls.py
"""Определяет схемы URL для learning_logs."""

from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
    #Домашняя страница
    path('', views.index, name='index'),
    #Страница со списком всех тем
    path('topics/', views.topics, name='topics'),
    #Страница с записями по выбранной теме
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    #Страница для добавления новой темы
    path('new_topic/', views.new_topic, name='new_topic'),
    #Страница для добавления новой записи по теме
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    #Страница для редактирования записи по теме
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),

]

django/learning_log/learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    """Тема, которую изучает пользователь"""
    id = models.BigAutoField(primary_key = True)
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Возвращает строковое представление модели"""
        return self.text


# Create your models here.
class Entry(models.Model):
    """Инфа, полученна пользователем по теме"""
    id = models.BigAutoField(primary_key = True)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Возвращает строковое представление модели"""
        if len(self.text) < 50:
            return self.text
        else:
            return f"{self.text[:50]}..."

django/learning_log/learning_logs/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': 'Entry:'}
        widgets = {'text' : forms.Textarea(attrs={'cols': 80})}

django/learning_log/learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

def check_user (request, topic):
    """Проверка текущего пользователя"""
    if topic.owner != request.user:
        raise Http404


def index(request):
    """Домашняя страница приложения learning_logs"""
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    check_user(request, topic)

    entries = topic.entry_set.order_by('-date_added') # "-" это обратное упорядочивание по дате 
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic (request):
    """Определяет новую тему"""
    if request.method != "POST":
        #Данные не отправлялись - создается пустая форма
        form = TopicForm()
    else:
        #Отправлены данные POST; обработать данные
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')

    #Вывести пустую или недействительную форму
    context = {'form': form}
    return render (request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Добавляет новую запись по конкретной теме"""
    topic = Topic.objects.get (id=topic_id)
    check_user(request, topic)

    if request.method != "POST":
        #Данные не отправлялись - создается пустая форма
        form = EntryForm()
    else:
        #Отправлены данные POST; обработать данные
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id = topic_id)

    #Вывести пустую или недействительную форму
    context = {'topic': topic, 'form': form}
    return render (request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Редактирование существующей записи"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    #Редактировать записи может только владелец
    check_user(request, topic)

    if request.method != "POST":
        #Исходный запрос; форма заполняется данными текущей записи
        form = EntryForm(instance=entry)
    else:
        #Отправлены данные POST; обработать данные
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id = topic.id)

    #Вывести пустую или недействительную форму
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render (request, 'learning_logs/edit_entry.html', context)

django/learning_log/learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1,
          shrink-to-fit=no">
        <title>Learning Log</title>

        {% bootstrap_css %}
        {% bootstrap_javascript jquery='full' %}

    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
            <a class="navbar-brand"  href="{% url 'learning_logs:index' %}">Learning log</a>
            <button class="navbar-togged" type="button" data-toggle="collapse"
                data-target="#navbarCollapse" aria-controls="navbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggled-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'learning_logs:topics'%}">Topics</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <span class="navbar-text">Hello, {{ user.username }}.</span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <main role="main" class="container">
            <div class="pb-2 mb-2 border-bottom">
                {% block page_header %}{% endblock page_header %}
            </div>
            <div>
                {% block content %}{% endblock %}
            </div>
        </main>
    </body>

</html>

django/learning_log/learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}


{% block page_header %}

<h3><a href="{% url 'learning_logs:topic' topic.id%}">{{topic}}</a></h3>
<h1>Edit entry</h1>

{% endblock page_header %}

{% block content %}

<!--<form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">save changes</button>
</form>-->

    <form method="post" action="{% url 'learning_logs:edit_entry' entry.id %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Save changes</button>
        {% endbuttons %}
        <input type="hidden" name="next"
          value="{% url 'learning_logs:topic' topic.id %}" />
    </form>



{% endblock content %}

django/learning_log/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block page_header %}

    <div class="jumbotron">
        {% if user.is_authenticated %}
            <h1 class="display-3">Track your learning, {{ user.username }}.</h1>
        {% else %}
            <h1 class="display-3">Track your learning.</h1>
        {% endif %}

        <p class="lead">Make your own learning log and keep a list of the topics
        you are learning about.</p>
        
        {% if user.is_authenticated == False %}
            <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
                role="button">Register &raquo;</a>
        {% else %}
            <a class="btn btn-lg btn-primary" href="{% url 'learning_logs:topics' %}"
                role="button">Go to my topics &raquo;</a>
        {% endif %}

    </div>

{% endblock page_header %}

django/learning_log/learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}


{% block page_header %}

<h3><a href="{% url 'learning_logs:topic' topic.id%}">{{topic}}</a></h3>
<h1>Add a new entry</h1>

{% endblock page_header %}

{% block content %}

    <form method="post" action="{% url 'learning_logs:new_entry' topic.id%}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Add entry</button>
        {% endbuttons %}
        <input type="hidden" name="next"
          value="{% url 'learning_logs:topic' topic.id %}" />
    </form>

{% endblock content %}

django/learning_log/learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
    <h1>Add a new topic</h1p>
{%endblock page_header%}

{% block content %}

    <form method="post" action="{% url 'learning_logs:new_topic' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Add topic</button>
        {% endbuttons %}
        <input type="hidden" name="next"
          value="{% url 'learning_logs:topics' %}" />
    </form>

{% endblock %}

django/learning_log/learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}


{% block page_header %}
    <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}

  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
  </p>

  {% for entry in entries %}
    <div class="card mb-3">
      <h4 class="header">
        {{ entry.date_added|date:'M d, Y H:i' }}
        <small>
          <a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>
        </small>
      </h4>
      <div class="card-body">
        {{ entry.text|linebreaks }}
      </div>
    </div>
  {% empty %}
    <p>There are no entries for this topic yet</p>
  {% endfor %}

{% endblock content %}

django/learning_log/learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}


{% block page_header %}
    <h1>Topics</h1>
{% endblock page_header %}

{% block content %}

<p>Topics</p>

<ul>
  {% for topic in topics %}
    <li><h3>
      <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    </h3></li>
  {% empty %}
    <li><h3>No topic have been added yet.</h3></li>
  {% endfor %}
</ul>

<h3><a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a></h3>

{% endblock %}